// Mock data for UI demonstration — replace with Supabase queries in production

export const MOCK_STATS = {
  totalMembers: 347,
  activeMembers: 289,
  totalChapters: 12,
  upcomingEvents: 5,
  revenueThisMonth: 4250,
  revenueYTD: 28750,
  pendingApprovals: 8,
  totalDonations: 12400,
};

export const MOCK_EVENTS = [
  {
    id: '1',
    title: 'Annual BUPEXSA USA Gala 2026',
    slug: 'annual-gala-2026',
    description: 'Our flagship annual dinner and awards ceremony celebrating alumni achievements and raising funds for scholarships.',
    start_datetime: '2026-06-14T18:00:00Z',
    end_datetime: '2026-06-14T23:00:00Z',
    location_name: 'Grand Ballroom, Marriott Marquis',
    location_address: '265 Peachtree Center Ave NE, Atlanta, GA 30303',
    category: 'Gala',
    thumbnail_path: '/images/events/gala.jpg',
    max_attendees: 300,
    is_published: true,
    rsvp_count: 187,
  },
  {
    id: '2',
    title: 'Texas Chapter Spring Meetup',
    slug: 'texas-spring-meetup-2026',
    description: 'A casual networking meetup for Texas chapter alumni. Come and reconnect with old classmates!',
    start_datetime: '2026-05-10T14:00:00Z',
    end_datetime: '2026-05-10T18:00:00Z',
    location_name: 'Allen\'s Landing Park',
    location_address: '100 Commerce St, Houston, TX 77002',
    category: 'Social',
    thumbnail_path: '/images/events/meetup.jpg',
    max_attendees: 80,
    is_published: true,
    rsvp_count: 34,
  },
  {
    id: '3',
    title: 'BUPEXSA Fundraiser Dinner — California',
    slug: 'california-fundraiser-2026',
    description: 'Join us for an evening of good food, great company, and impactful fundraising for PCSS Buea.',
    start_datetime: '2026-07-20T17:30:00Z',
    end_datetime: '2026-07-20T22:00:00Z',
    location_name: 'The Biltmore Hotel',
    location_address: '506 S Grand Ave, Los Angeles, CA 90071',
    category: 'Fundraiser',
    thumbnail_path: '/images/events/fundraiser.jpg',
    max_attendees: 150,
    is_published: true,
    rsvp_count: 61,
  },
  {
    id: '4',
    title: 'Annual General Meeting 2026',
    slug: 'agm-2026',
    description: 'The annual general meeting for all BUPEXSA USA members to elect officers and vote on key resolutions.',
    start_datetime: '2026-09-05T10:00:00Z',
    end_datetime: '2026-09-05T16:00:00Z',
    location_name: 'Virtual (Zoom)',
    location_address: 'Online',
    category: 'Meeting',
    thumbnail_path: '/images/events/agm.jpg',
    max_attendees: null,
    is_published: true,
    rsvp_count: 112,
  },
];

export const MOCK_CHAPTERS = [
  {
    id: '1',
    name: 'Texas Chapter',
    slug: 'texas',
    state: 'Texas',
    description: 'Serving BUPEXSA USA alumni across the great state of Texas, including Houston, Dallas, Austin, and San Antonio.',
    is_active: true,
    member_count: 84,
    banner_image_path: '/images/chapters/texas.jpg',
  },
  {
    id: '2',
    name: 'Georgia Chapter',
    slug: 'georgia',
    state: 'Georgia',
    description: 'The Atlanta-based hub connecting alumni in Georgia and the greater Southeast region.',
    is_active: true,
    member_count: 56,
    banner_image_path: '/images/chapters/georgia.jpg',
  },
  {
    id: '3',
    name: 'California Chapter',
    slug: 'california',
    state: 'California',
    description: 'Uniting BUPEXSA graduates across Los Angeles, San Francisco, San Diego, and all of California.',
    is_active: true,
    member_count: 71,
    banner_image_path: '/images/chapters/california.jpg',
  },
  {
    id: '4',
    name: 'Maryland / DC Chapter',
    slug: 'maryland-dc',
    state: 'Maryland, DC',
    description: 'Serving alumni in the greater DMV area — DC, Maryland, and Northern Virginia.',
    is_active: true,
    member_count: 48,
    banner_image_path: '/images/chapters/maryland.jpg',
  },
  {
    id: '5',
    name: 'New York Chapter',
    slug: 'new-york',
    state: 'New York',
    description: 'The New York City metro area chapter, one of our most active and vibrant communities.',
    is_active: true,
    member_count: 63,
    banner_image_path: '/images/chapters/newyork.jpg',
  },
  {
    id: '6',
    name: 'North Carolina Chapter',
    slug: 'north-carolina',
    state: 'North Carolina',
    description: 'Connecting alumni in Charlotte, Raleigh, Durham, and across the Tar Heel State.',
    is_active: true,
    member_count: 25,
    banner_image_path: '/images/chapters/nc.jpg',
  },
];

export const MOCK_ANNOUNCEMENTS = [
  {
    id: '1',
    title: 'Registration Open: Annual Gala 2026',
    body: 'Tickets are now available for our highly anticipated Annual Gala in Atlanta. Secure your seat before they sell out!',
    publish_date: '2026-04-01',
    is_published: true,
  },
  {
    id: '2',
    title: 'Scholarship Applications Due May 31',
    body: 'BUPEXSA USA is awarding $5,000 in scholarships to deserving students at PCSS Buea. Applications close May 31st.',
    publish_date: '2026-04-10',
    is_published: true,
  },
  {
    id: '3',
    title: 'New Chapter Launched: Pacific Northwest',
    body: 'We are excited to announce the formation of our Pacific Northwest Chapter covering Washington, Oregon, and Idaho.',
    publish_date: '2026-04-15',
    is_published: true,
  },
];

export const MOCK_LEADERSHIP = [
  {
    id: '1',
    name: 'Dr. Emmanuel Fon',
    title: 'National President',
    chapter: 'National',
    bio: 'Dr. Fon is a cardiologist based in Atlanta, GA. Class of 1992. He has led BUPEXSA USA\'s expansion from 3 chapters to 12 since 2022.',
    photo_path: '/images/leadership/president.jpg',
    order: 1,
  },
  {
    id: '2',
    name: 'Mrs. Grace Mbah-Taylor',
    title: 'National Secretary General',
    chapter: 'National',
    bio: 'Grace is an attorney based in New York City. Class of 1998. She serves as the organizational backbone of BUPEXSA USA.',
    photo_path: '/images/leadership/secretary.jpg',
    order: 2,
  },
  {
    id: '3',
    name: 'Mr. Patrick Nkeng',
    title: 'National Treasurer',
    chapter: 'National',
    bio: 'Patrick is a financial analyst based in Houston, TX. Class of 2001. He oversees all financial operations and reporting.',
    photo_path: '/images/leadership/treasurer.jpg',
    order: 3,
  },
  {
    id: '4',
    name: 'Dr. Barbara Che',
    title: 'VP Membership',
    chapter: 'National',
    bio: 'Barbara is a pharmacist based in Maryland. Class of 2005. She leads membership growth and engagement initiatives.',
    photo_path: '/images/leadership/vp.jpg',
    order: 4,
  },
  {
    id: '5',
    name: 'Eng. Samuel Awah',
    title: 'VP Events & Programs',
    chapter: 'National',
    bio: 'Sam is a software engineer in California. Class of 2008. He coordinates our national events and cultural programs.',
    photo_path: '/images/leadership/events.jpg',
    order: 5,
  },
  {
    id: '6',
    name: 'Mrs. Claudette Ngwa',
    title: 'Communications Director',
    chapter: 'National',
    bio: 'Claudette is a marketing professional in North Carolina. Class of 2010. She manages all BUPEXSA communications and social media.',
    photo_path: '/images/leadership/comms.jpg',
    order: 6,
  },
];

export const MOCK_GALLERY = [
  { id: '1', category: 'Gala', alt: 'Annual Gala 2025 dinner event', path: '/images/gallery/gala1.jpg' },
  { id: '2', category: 'Gala', alt: 'Awards ceremony at Gala', path: '/images/gallery/gala2.jpg' },
  { id: '3', category: 'Meetups', alt: 'Texas chapter spring meetup', path: '/images/gallery/meetup1.jpg' },
  { id: '4', category: 'Meetups', alt: 'California alumni gathering', path: '/images/gallery/meetup2.jpg' },
  { id: '5', category: 'PCSS Buea', alt: 'PCSS Buea main campus', path: '/images/gallery/pcss1.jpg' },
  { id: '6', category: 'PCSS Buea', alt: 'Historic school building', path: '/images/gallery/pcss2.jpg' },
  { id: '7', category: 'Community', alt: 'Scholarship award ceremony', path: '/images/gallery/community1.jpg' },
  { id: '8', category: 'Community', alt: 'Community outreach event', path: '/images/gallery/community2.jpg' },
];

export const SITE_CONFIG = {
  name: 'BUPEXSA USA',
  tagline: 'Connecting PCSS Buea Alumni Across America',
  description: 'BUPEXSA USA is the official alumni association of Presbyterian College Secondary School Buea, uniting graduates residing in the United States.',
  url: process.env.NEXT_PUBLIC_SITE_URL || (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://bupexsausa.org'),
  email: 'info@bupexsausa.org',
  phone: '+1 (404) 555-0123',
  address: 'P.O. Box 12345, Atlanta, GA 30301',
  membershipFee: 75,
  socialLinks: {
    facebook: 'https://facebook.com/bupexsausa',
    instagram: 'https://instagram.com/bupexsausa',
    twitter: 'https://twitter.com/bupexsausa',
    youtube: 'https://youtube.com/@bupexsausa',
    whatsapp: 'https://wa.me/14045550123',
  },
  zelleHandle: 'payments@bupexsausa.org',
  cashappHandle: '$BUPEXSAusa',
};
